# -*- coding: utf-8 -*-
"""tarefa3_sprint8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16J01CJ_OAGixZsSSthzJLrgGQWK6JheY

[Warm up]  Em Python, declare e inicialize uma lista contendo 250 inteiros obtidos de forma aleatória. Após, aplicar o método reverse sobre o conteúdo da lista e imprimir o resultado.
"""

import random

inteiros_aleatorios = [random.randint(1,1000) for _ in range(250)]

inteiros_aleatorios.reverse()

print(inteiros_aleatorios)

"""[Warm up] Em Python, declare e inicialize uma lista contendo o nome de 20 animais. Ordene-os em ordem crescente e itere sobre os itens, imprimindo um a um (você pode utilizar list comprehension aqui).  Na sequência, armazene o conteúdo da lista em um arquivo de texto, um item em cada linha, no formato CSV."""

animais = ["Cachorro", "Gato", "Elefante", "Leão", "Tigre", "Girafa", "Zebra", "Macaco", "Rinoceronte", "Panda",
           "Cavalo", "Coelho", "Pássaro", "Gavião", "Crocodilo", "Pinguim", "Baleia", "Tubarão", "Peixe"]

animais.sort()

print('Lista de animais em ordem crescente:')
[print(animal) for animal in animais]

with open('animais.csv','w') as arquivo_animais:
  for animal in animais:
    arquivo_animais.write(animal + '\n')

"""[Laboratório] Elaborar um código Python para gerar um dataset de nomes aleatórios de pessoas."""

# Passo 1:  Instalar biblioteca names para geração de nomes aleatórios
pip install names

# Passo 2 Importar as bibliotecas random, time, os e names em seu código
import names
import time
import random
import os

# Passo 3: Definir os parâmetros para geração do dataset, ou seja, a quantidades de nomes aleatórios e a quantidade de nomes que devem ser únicos.
random.seed(40)
qtd_nomes_unicos = 3000
qtd_nomes_aleatorios = 10000000

# Passo 4: Gerar os nomes aleatórios.
aux = []

# loop para gerar e armazenar números aleatórios únicos na lista aux
for i in range (0, qtd_nomes_unicos):
  aux.append(names.get_full_name())

# Passo 5: Gerar um arquivo de texto contendo todos os nomes, um a cada linha.
dados = []

for i in range(0,qtd_nomes_aleatorios):
    dados.append(random.choice(aux))

print("Gerando {} nomes aleatórios".format(qtd_nomes_aleatorios))

with open('nomes_aleatorios.txt', 'w') as arquivo_nomes:
    for nome in dados:
        arquivo_nomes.write(nome + '\n')